# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 402c4c392b28c8a03002df6a3925eae4eda6afceda973d024e8c3085653a40cf8ef0c6c0f5a79f819bf2caf6a9e4bba732e4c4394e4287aa97702ae240115b03

test:
  secret_key_base: cf5fb15e1d00c0cf0283c6cb12427e29ead7ba2ecff3d9004bdf4922755b3926bebb2be57ede5a097c9a600c63362695440cbbe8cc3e77253b0af8d18290b5b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
